export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  icons: {
    icon: "/white-logo3.svg",
    shortcut: "/white-logo3.svg",
    apple: "/white-logo3.svg",
    other: {
      rel: "apple-touch-icon-precomposed",
      url: "/white-logo3.svg",
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
