
import "../globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Header } from "./header/Header";
import  Sidebar  from "./aside/Sidebar";
config.autoAddCss = false;
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="all-x">
          <Header />
          <Sidebar />
          <div className="x-container">{children}</div>
          <footer className="bg-gray-800 text-white py-6 text-center">
            <p>
              &copy; {new Date().getFullYear()} Educational Academy. All rights
              reserved.
            </p>
          </footer>
        </div>
      </body>
    </html>
  );
}
